federation_version: =2.8.1

subgraphs:
  property:
    routing_url: http://property-api:4001
    schema:
      file: ../data-products/property/schema.graphql

  leasing:
    routing_url: http://leasing-api:4002
    schema:
      file: ../data-products/leasing/schema.graphql

  finance:
    routing_url: http://finance-api:4003
    schema:
      file: ../data-products/finance/schema.graphql